---
- hosts: all

- hosts: localhost
  roles:
    - terraform

- hosts: webservers
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - webservers
    - { role: datadog.datadog, become: yes }
