all:
  children:
    webservers:
      hosts:
#        w[01:03].redmine.local
        164.90.170.24
#      vars:
#    db:
#      hosts:
#        d01.redmine.local
  vars:
#    ansible_connection: ssh
    ansible_user: root
#    ansible_become_pass: "{{ srv_become_pass }}"
    ansible_python_interpreter: /usr/bin/python3
